### ISSUE TITLE
Remontée RC et recyclage - Ogame v6.3.5

### ISSUE THREAD

**Issue by Roms0406** [OGSteam/tool-xtense-web-extension#1]
Les attaques et les recyclages ne remontent plus depuis la mise à jour Ogame v6.3.5

**Comment by Itori** [comment]
Correction partielle avec OGSteam/tool-xtense-web-extension@9f28c05

**Comment by darknoon29** [comment]
@Itori Quel est le format pour le Mod Xtense ? Est ce ce que tu as un exemple de requête ?

**Comment by Itori** [comment]
Je récupère le JSon complet.
[rapport.zip](https://github.com/OGSteam/tool-xtense-web-extension/files/722091/rapport.zip)

**Comment by Itori** [comment]
Récupération des RC : ok
Récupération des recyclages : ok
