### ISSUE TITLE
Pourrais t-on déplacer les options de Xtense dans un Menu spécifique au module

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/tool-xtense-web-extension#10]
Il serait possible d'effectuer la configuration du mod en cliquant sur l'icône du mod au lieu d'avoir une insertion dans la page Ogame.

Qu'en pensez vous ?

Exemple d'un autre mod  

![image](https://cloud.githubusercontent.com/assets/13015521/24375109/70f03ed2-1337-11e7-9530-c67f902b9b3e.png)

**Comment by Itori** [comment]
J'ai regardé pour faire ça, c'est effectivement possible mais pas forcément simple avec l'application en l'état.

**Comment by darknoon29** [comment]
En fait j'ai regardé mais je n'ai pas trouvé de solution à la fois compatible Chrome et Firefox :P

**Comment by darknoon29** [comment]
> En fait j'ai regardé mais je n'ai pas trouvé de solution à la fois compatible Chrome et Firefox :P

Probablement à fermer du coup

**Comment by darknoon29** [comment]
Le jeu prévoit un emplacement pour les mods. Nous l'avons utilisé et pas besoin de menu supplémentaire.
