### ISSUE TITLE
Xtense ne détecte aucun allié sur la page alliance

### ISSUE THREAD

**Issue by loclamor** [OGSteam/tool-xtense-web-extension#14]
serveur s146-fr
le Xpath XtenseXpaths.ally_members_list ne retourne rien. (Ogame.js:305)

**Comment by darknoon29** [comment]
Je n'ai pas d'alliance en ce moment :P 

Tu peux nous aider sur le debug ?

**Comment by loclamor** [comment]
Salut,

J'ai un peut investigué : 
ce n'est pas le xpath qui pose problème, lorsque exécuté manuellement une fois la page chargée, celui-ci semble OK.
Seulement, la fonction parse_ally_inserted (Ogame.js:305) est appelée alors que le contenu de la page de l'alliance est entrain de se charger en ajax (index.php?page=allianceOverview).
Après, on rentre bien dans la fonction get_ally_content (Ogame.js:338) qui a par ailleur un petit commentaire "Pourquoi celui-ci est fait à l'envers par rapport aux autres ?"
get_ally_content (Ogame.js:136) crée un MutationObserver qui n'a du coup pas l'air de faire son boulot, puisque parse_ally_inserted n'est jamais rappelée.

Peut être faudrait il déclarer l'observer plus tôt, comme pour la gestion des messages ?
Cela reviendrait à remplacer/ou à ajouter la ligne 49 : get_ally_content() ?

**Comment by Itori** [comment]
N'ayant plus de compte Ogame, je ne peux pas tester et vérifier cependant voici ce que je vois :

Il n'y a pas de MutationObserver pour cette page.
Si tu prend la fonction get_content (Ogame.js:82), il n'y a pas d'elementName de défini pour la page alliance, donc tu passe en traitement direct.

Ce qu'il faut regarder, c'est quel est l'encapsulant (probablement un div) qui est modifié lors de l'appel ajax, et le définir comme elementName (Ogame.js:115), en faisant cela, on va utiliser le MutationObserver qui va déclencher parse_ally_inserted lorsque l'élément sera modifié.

**Comment by darknoon29** [comment]
Je vois ce log : 
Xtense says : Universe Number: 140
Xtense says : Universe language: fr
Xtense says : setStatus : Xtense est prêt
Xtense says : setStatus : Liste des joueurs alliés détectée
Xtense says : 1 membres à envoyer !

Mais aucune requête ne part ensuite.

**Comment by darknoon29** [comment]
Bon j'ai pu trouver ce qui n'allait pas : la structure HTML a changé sur cette section.

J'ai revu très légèrement les Xpath et c'est bon chez moi ;-)

**Comment by loclamor** [comment]
Pas sur que cela la correction règle le problème chez moi. En effet, chez moi le log ressemble à ça : 
```
Xtense says : Universe Number: 146
Xtense says : Universe language: fr
Xtense says : setStatus : Xtense est prêt
Xtense says : setStatus : Liste des joueurs alliés détectée
Xtense says : 0 membres à envoyer !
```
Alors qu'il y a une vingtaine de membres dans mon ally.
Pour info, comme dit plus haut, la xpath rows retourne bien le bon nombre de ligne, lorsque exécutée manuellement après chargement complet de la page.
A mon sens, la fonction parse_ally_inserted est appelée trop tôt, et n'est jamais rappelée lorsque le contenu de la page change (que la liste des alliés est affichée).

**Comment by darknoon29** [comment]
J'ai crée une version Alpha de Xtense avec le correctif : https://addons.mozilla.org/fr/firefox/addon/xtense-we/versions/beta?page=1#version-2.7.8alpha1

**Comment by loclamor** [comment]
Intéressant : le correctif fonctionne... sous firefox. J'utilisais Chrome précedement.

Sous firefox du coup, avec la version actuelle du plugin : 
```
Xtense says : Universe Number: 146
Xtense says : Universe language: fr
Xtense says : setStatus : Xtense est prêt
Xtense says : setStatus : Liste des joueurs alliés détectée
Xtense says : 24 membres à envoyer !
```

Avec le correctif, la liste est bien envoyé au serveur.

Sous chrome, en revanche, sur la version actuelle, 
```
Xtense says : 0 membres à envoyer !
```

**Comment by darknoon29** [comment]
Pour chrome tu as chargé l'extension depuis les sources Github?

**Comment by loclamor** [comment]
non, depuis le Chrome Web Store (https://chrome.google.com/webstore/detail/xtense-gm/mkcgnadlbcakpmmmdfijdekknodapcgl?utm_source=chrome-app-launcher-info-dialog)

**Comment by darknoon29** [comment]
Oui donc ce que tu vois est normal vu que je n'ai encore rien poussé sur le store chrome

**Comment by loclamor** [comment]
Oui, mais ce que je disais, c'est que j'ai eu le problème initial avec chrome : "Xtense says : 0 membres à envoyer !"

**Comment by darknoon29** [comment]
Hello, J'ai activé le détection de modifications de la page par Ajax sur la section alliance.

J'ai testé chez moi et ça se passe mieux pour Chrome. Tu pourras me confirmer que c'est bon de ton côté ?

https://github.com/OGSteam/tool-xtense-web-extension/commit/8a246dbcafba1896c9d0a7ff9353111a7fd1d844

La modification est minime car la mécanique était déjà en place ;-)

**Comment by darknoon29** [comment]
Tu as pu tester avec Chrome ? Sinon je diffuse tel quel sur le store Google et tu me diras après😉

**Comment by loclamor** [comment]
Fait cela, oui, car je n'ai pas pu tester, j'ai eu un soucis avec mon serveur OGSpy hier aprem et ce matin

**Comment by loclamor** [comment]
Hello,
Ca a l'air de marcher, Xtense envoie bien les données à mon OGSpy. Par contre, j'ai un message "Code réponse inconnu" sur le retour du serveur : 
```
Xtense says : Response: {"new_messages":0,"execution":"3.58"}
Xtense says : setStatus : [3.58 ms][OGSpy] Code réponse inconnu
```

**Comment by darknoon29** [comment]
Cool! Oui il reste un soucis du côté du module OGSpy. Je dois encore pousser la version pour les utilisateurs Firefox
