### ISSUE TITLE
Messages not sent to ogspy

### ISSUE THREAD

**Issue by injNinja** [OGSteam/tool-xtense-web-extension#15]
Hi, Xtense is ready and recognizes the messages page, but it doesnt send any message.

Is there a particular configuration i have to do?

Thank you

**Comment by darknoon29** [comment]
Hi, 
Could you share your ogame universe URL? Thanks!

**Comment by injNinja** [comment]
https://s115-it.ogame.gameforge.com

Thank you man!

**Comment by darknoon29** [comment]
From your URL, Italian is not supported yet. 

You could help us by translating (with some friends) all the strings on this site :

https://www.transifex.com/ogsteam/ogspy/

Based on  that work  we will make a release that supports Italian and check the result ☺️

**Comment by injNinja** [comment]
Got it, i found the problem activating the debug :)

What part of ogspy do you need to be translated? Both ogspy + xtense or only xtense?

**Comment by darknoon29** [comment]
In fact message parsing needs text references to get the data. As we are in a different language we need to add it in the source of the extension. (parsers/ogame locales.js)

I usually use translated files to update this particular file 😉

**Comment by injNinja** [comment]
OGSpy translated fully while waiting for a Combat report :) 
I requested access to Xtense GM team and requested italian! 

Thank you!

**Comment by darknoon29** [comment]
I saw and accepted your request concerning Italian on transfex but where is your request concerning xtense gm? Is it on Github?

**Comment by darknoon29** [comment]
On Github you just need to create a pull request to share your changes 😉

**Comment by injNinja** [comment]
No the concern is all about the translation of XtenseGM on transifex :) Do i need to do anything else or is it fine once i finished the translation on it?

**Comment by injNinja** [comment]
I found that maybe i have to modify event OgameLocales.js in the Xtense/parsers folder with italian names, is it right? Im not very used to Github, thank you!

**Comment by darknoon29** [comment]
Have you tested the latest Xtense Browser Module ?

**Comment by injNinja** [comment]
Sorry but was a bit busy these days. Btw I tested it, espionage reports are quite good but they don't show correct mines level/resources. In addition to this, expeditions are not recognized!



Inviato da iPhone

**Comment by darknoon29** [comment]
Did you get a chance to test the latest version?

**Comment by darknoon29** [comment]
I have reproduced the problem :-) Will publish a fix soon !

**Comment by injNinja** [comment]
great!! i’m back to italy right now, so i can help with testing!! thank you a anthony!

Inviato da iPhone
