### ISSUE TITLE
configuration du module xtense

### ISSUE THREAD

**Issue by children07** [OGSteam/tool-xtense-web-extension#18]
Bonsoir
j'ai un soucis sans doute assez bête à résoudre mais je n arrive pas a faire correspondre mon module xtense sur mon serveur ogspy il me met 
La configuration du module xtense de votre ogspy, ne correspond pas a votre univers de jeu, merci de vérifier que le lien vers le serveur ogame est correctement renseigné.

je me gratte la tete depuis car sur mon ogspy  ben finalement y'a rien 
merçi pour votre retour 
cordialement

**Comment by darknoon29** [comment]
Hello,

Tu as une configuration à faire sur ton site OGSpy pour configurer ton univers. C'est dans le menu de gauche : Modules -> Xtense 

Tu auras des captures d'écran dans notre wiki : https://wiki.ogsteam.fr/doku.php?id=fr:ogspy:documentationxtense#espace_administrateur

Bonne soirée,

Dark

**Comment by children07** [comment]
Je l avait vu ce wiki 
J'ai fait le rapprochement 
Il suffisait de prendre l adresse de mon univers en lien et le remplacer 🤣😉
Ig  mon extense  (x) est en vert ^^
Mise à jour vue général. Cependant sur ogspy aucune info est remonter pourtant la totalité des cases extense est coché aucune info ce met sur la cartographie et ou autre infos des modules installée 
Je pense qu'après jesper en profiter 
Merci à toi 
Children

**Comment by children07** [comment]
Y'a une autre démarche particulière que j'ai pas pu explorer ?

**Comment by darknoon29** [comment]
Toutes les informations ne remontent pas ?

**Comment by darknoon29** [comment]
On commence normalement par la vue générale des planètes

**Comment by children07** [comment]
Je te remercie en tout cas pour le suivi
très agréable d être bien aider
cordialement
________________________________
De : Anthony <notifications@github.com>
Envoyé : lundi 13 novembre 2017 23:03
À : OGSteam/tool-xtense-web-extension
Cc : children07; Author
Objet : Re: [OGSteam/tool-xtense-web-extension] configuration du module xtense (#18)


Hello,

Tu as une configuration à faire sur ton site OGSpy pour configurer ton univers. C'est dans le menu de gauche : Modules -> Xtense

Tu auras des captures d'écran dans notre wiki : https://wiki.ogsteam.fr/doku.php?id=fr:ogspy:documentationxtense#espace_administrateur

Bonne soirée,

Dark

**Comment by darknoon29** [comment]
Merci pour ton retour. Machine à fait une vidéo pour expliquer les installations (Sur notre forum ou la board ogame)
