### ISSUE TITLE
Version incompatible

### ISSUE THREAD

**Issue by ketchupilevrai** [OGSteam/tool-xtense-web-extension#25]
Bonjour, j'ai ce message : La version du mod extense installé sur votre serveur est incompatible avec votre plugin.

J ai xtense GM 2.7.13 sur chrome et Xtense 2.7.2 sur ogspy.

C'est une installation neuve. j ai juste utiliser les versions fournies par defaut

je ne vois pas ce que je fais mal ...

**Comment by ketchupilevrai** [comment]
là ou je les aient eu ?

**Comment by ketchupilevrai** [comment]
j ai tout pris ici, et j ai fait les mises a jour avec autoupdate.
Je vais refaire tout a 0 sans mises a jour je penses..

[https://forum.ogsteam.fr/index.php?topic=1187.0](https://forum.ogsteam.fr/index.php?topic=1187.0)

**Comment by darknoon29** [comment]
Oui ce que tu as téléchargé. Pour m'assurer que je vérifie les mêmes fichiers que les tiens

**Comment by darknoon29** [comment]
OK dans ce cas privilégie ce package : https://github.com/OGSteam/ogspy/releases/download/3.3.2/ogspy-3.3.2.zip

**Comment by ketchupilevrai** [comment]
ok merci je lance ca

**Comment by ketchupilevrai** [comment]
c'est pareil :/ j'ai juste installer ogspy et le module xtense dessus, rien d autre

**Comment by darknoon29** [comment]
Tu as pris toutes les mise à jour dans le le mod autoupdate d'OGSpy?

**Comment by ketchupilevrai** [comment]
je n'es rien mis du tout justement
j 'ai laissé d'origine

**Comment by ketchupilevrai** [comment]
ah yes ! c'est good apres maj en 2.7.3 avec autoupdate

**Comment by ketchupilevrai** [comment]
je ne comprend pas le probleme vraiment mais du coup ca marche comme ca. merci

**Comment by darknoon29** [comment]
Cool. De mon côté je dois remettre à jour le package
