### ISSUE TITLE
Améliorer la gestion des messages

### ISSUE THREAD

**Issue by Itori** [OGSteam/tool-xtense-web-extension#3]
- [x] Gestion du chargement asynchrone des messages
- [x] Améliorer la détection des messages envoyés

**Comment by darknoon29** [comment]
Peut être en lien avec le rapport d'erreur... Quels sont les infos que tu vas récupérer ici pour la détection ?

**Comment by Itori** [comment]
Pas compris la question

**Comment by darknoon29** [comment]
Ah c'est parque je n'ai pas compris le bug en fait :-)

**Comment by Itori** [comment]
Oh, comme je le marque c'est la gestion des messages asynchrones ^^
Le chargement des messages est faite par une requête ajax, et du coup le chargement de la page est terminé avant que le chargement des messages ne soit fait.

Le déclanchement d'xtense est fait à la fin du chargement, ce qui fait que certains messages ne sont pas traités automatiquement.
Par exemple, les messages d'espionnage (au format court) ne sont pas traités directement, il est nécessaire de faire un clic sur le message pour déclancher.

Concernant l'amélioration de la détection, je ne sais plus exactement :/

**Comment by darknoon29** [comment]
Ah pour ça il y a peut être une config qui pourrait t'interesser dans le manifest.json :+1: 

      "run_at": "document_idle"

**Comment by darknoon29** [comment]
J'ai modifié dans le dernière version quelques paramètres de détection des changements dans les mutation observer. Est ce que c'est mieux ?

**Comment by darknoon29** [comment]
Corrigé avec PR#27
