### ISSUE TITLE
Data from spy reports incomplete

### ISSUE THREAD

**Issue by juliogonzalez** [OGSteam/tool-xtense-web-extension#31]
Example:
![image](https://user-images.githubusercontent.com/4226070/55675855-53da5880-58c9-11e9-9799-bb327b2493fa.png)
And at OGspy:
![image](https://user-images.githubusercontent.com/4226070/55675862-78cecb80-58c9-11e9-9008-8f0ec0395e2e.png)

Only the data for metal seems is present. Other values are -1.

There's no info about defense, fleets, or technologies, but since the tables at OGSpy don't show them, I guess that's simply unsupported yet.

Language: Spanish (s159-es)
OGspy: 3.3.4
Xtense Module: 2.7.4
Web plugin: 2.7.23

This is from the web console, maybe the most relevant part is the message at `1554588751085`
```
[1554588751016] Xtense : Mutation Message
utilities.js:63 [1554588751016] Xtense : setStatus : Message page detected
utilities.js:63 [1554588751019] Xtense : ID Message court : 4808023
utilities.js:63 [1554588751019] Xtense : ID Message court : 4808015
utilities.js:63 [1554588751020] Xtense : ID Message court : 4790641
utilities.js:63 [1554588751021] Xtense : ID Message court : 4783198
utilities.js:63 [1554588751021] Xtense : ID Message court : 4783149
utilities.js:63 [1554588751022] Xtense : ID Message court : 4783049
utilities.js:63 [1554588751023] Xtense : ID Message court : 4781396
utilities.js:63 [1554588751025] Xtense : ID Message court : 4781118
utilities.js:63 [1554588751026] Xtense : ID Message court : 4778183
utilities.js:63 [1554588751027] Xtense : ID Message court : 4714149
utilities.js:63 [1554588751027] Xtense : Message Long messageid : 4783149
utilities.js:63 [1554588751028] Xtense : Traitement du message
utilities.js:63 [1554588751030] Xtense : Message espionnage détecté
utilities.js:63 [1554588751033] Xtense : setStatus : Spy report detected
utilities.js:63 [1554588751085] Xtense : sending toolbar_version=2.7.23&toolbar_type=GM-GC&mod_min_version=2.7.4&user=XXXXXXXXXX&password=XXXXXXXXXX&univers=https://s159-es.ogame.gameforge.com&type=messages&lang=es&data[date]=1554566754&data[type]=spy&data[planetName]=en%20Planeta%20Principal&data[coords]=4%3A211%3A12&data[proba]=0&data[activity]=20&data[content][metal]=71420&data[playerName]=llucmuerte&data[moon]=0&data[ogapilnk]=sr-es-159-c99f3dd1245c62e88edd6dbf419fac9244ad9b9f to https://docker.hispa-net.com/ogspy//mod/xtense/xtense.php from https://s159-es.ogame.gameforge.com
utilities.js:63 [1554588751086] Xtense : Message spysent
[Violation] Forced reflow while executing JavaScript took 46ms
utilities.js:63 [1554588751250] Xtense : Status: 200
utilities.js:63 [1554588751250] Xtense : Response: {"new_messages":0,"type":"messages","execution":"19.94"}
utilities.js:63 [1554588751251] Xtense : setStatus : [19.94 ms][OGSpy] Message has been sent to your OGSpy.
```
I don't have anything relevant at the OGSpy server logs.

The plugin config:
![image](https://user-images.githubusercontent.com/4226070/55676095-e1b84280-58cd-11e9-89a0-eb91f3f95b12.png)

**Comment by juliogonzalez** [comment]
Not sure, but maybe there's something at https://github.com/OGSteam/tool-xtense-web-extension/blob/master/extension/parsers/MessagesParser.js#L566

My understanding is that the function is parsing the XHTM raw document, and that the all the data should be present at `spyStrings`, but I am afraid I can't understand the code very well.

**Comment by bokybanton** [comment]
Exactly the same problem. Some spy reports have ships but cristal and deuterium always shows -1.

**Comment by darknoon29** [comment]
Hello here, could you share the Html page source on gist ?

I will be able to fix that issue with it. Thanks

**Comment by darknoon29** [comment]
No Answer. Will check with Ogame Fr
