### ISSUE TITLE
Pas de réponse serveur

### ISSUE THREAD

**Issue by clo275** [OGSteam/tool-xtense-web-extension#32]
Bonjour,
j'ai mis à jour par l'intermédiaire du site Xtense vers la V 3.3.6
depuis côté Ogame je n'ai que la croix rouge et pas de réponse serveur lorsque je survole celle-ci avec la souris.
Pouvez-vous m'aider, svp ?
Cordialement 
shinra univers s135 - Izar -

**Comment by darknoon29** [comment]
@clo275 Il y a un nouveau système de mot de passe. Tu trouveras le nouveau mot de passe dans la page d'accueil du Mod Xtense dans ton site OGSpy

**Comment by clo275** [comment]
J'ai fait un copié collé de la clé en question

**Comment by clo275** [comment]
J'ai fait un copié collé de la clé en question dès hier et cela me fait ce qui est indiqué dans mon premier message

**Comment by darknoon29** [comment]
Tu peux me faire un screenshot de ta config côté navigateur ainsi que les logs du navigateur ? 
F12 -> Console avec le mode debug activé dans les paramètres Xtense du Navigateur.

Ou sinon tu le poste sur Discord.

**Comment by clo275** [comment]
Voici 4 "imprime écran" j'espère que c'est ce que tu souhaites

identifiant ; shinra
mdp : 2QhEU26Qogs

[aide_Xtense_OGSpy.docx](https://github.com/OGSteam/tool-xtense-web-extension/files/3354889/aide_Xtense_OGSpy.docx)

**Comment by darknoon29** [comment]
Le lien OGSpy dans l'extension du navigateur doit être https://ogspy.fr/shinra

Je vois que j'ai un Bug côté OGSpy sur cet affichage...

**Comment by clo275** [comment]
C'est beaucoup mieux, merci
encore une petite croix rouge sur l'envoi des galaxies, alors que ça arrive bien sur le site, avec simplement un problème d'heure indiquée, décalage de 5 minutes
3 nouveaux "imprime écran"
[2_aide_Xtense_OGSpy.docx](https://github.com/OGSteam/tool-xtense-web-extension/files/3355308/2_aide_Xtense_OGSpy.docx)

**Comment by darknoon29** [comment]
Merci pour le screenshot : On voit que c'est un Bug du mod Oversight qui t'empêche d'avoir une réponse correcte. Je vais créer le Bug là bas.

**Comment by darknoon29** [comment]
Done
