### ISSUE TITLE
Bug remonté page techno

### ISSUE THREAD

**Issue by yopshot** [OGSteam/tool-xtense-web-extension#40]
Depuis la V7 ogame (et/ou la version 2.8.3 du plugin?) la remontée de la page techno mélange les valeurs.
Voici le lien envoyé à OGSpy trouvé dans la console en débug. 
https://s158-fr.ogame.gameforge.com/&type=researchs&planet_name=P1-1&coords=1%3A91%3A15&planet_type=0&NRJ=16&Laser=5&Ions=9&Hyp=12&Plasma=14&RC=12&RI=8&PH=14&Esp=16&Ordi=17&Astrophysique=5&RRI=13&Graviton=13&Armes=14&Bouclier=undefined&Protection=undefined

Forcément le même résultat se retrouve dans la BDD ogspy. 

Mes techs si ça peu aider: 
espio : 14 / ordi: 16 / armes : 13 / bouclier : 13 / protection : 14 / NRJ : 16
HYyp : 9 / RC: 14 / RI : 12 / PH: 8 / laser: 12 / ions: 5 / plasma : 12
rri : 5 / graviton : 1 / astro: 17

Cdt

**Comment by darknoon29** [comment]
Corrigé
