### ISSUE TITLE
Lecture d'un RE d'une position ayant un CDR 

### ISSUE THREAD

**Issue by Chouette-ogame** [OGSteam/tool-xtense-web-extension#44]
Lors de l'envoi du RE suivant : 

![image](https://user-images.githubusercontent.com/65313224/81864349-c9a10100-956c-11ea-9e8e-73a1438d3030.png)

OGSpy interprète le CdR comme étant les ressources à quai sur la planète : 

![image](https://user-images.githubusercontent.com/65313224/81864431-e9d0c000-956c-11ea-93ac-14f8e160f2dc.png)

**Comment by darknoon29** [comment]
Les valeurs métal et cristal s'ecrasaient. Il faut revenir au ressource code pour bien séparer les données.

**Comment by darknoon29** [comment]
Corrigé en version 2.9.4
