### ISSUE TITLE
Les données envoyées ont été refusées par le plugin Xtense

### ISSUE THREAD

**Issue by WAT02110** [OGSteam/tool-xtense-web-extension#51]
Bonjour,
après la configuration de ogspy et du plugin xtense, il m'est impossible d'envoyer des données, j'ai toujours ce message:
"Les données envoyées ont été refusées par le plugin Xtense"

Sur mozilla ou Chrome j'ai la meme chose.
Xtense 2.9.6

comment puis je debuger ?

Merci

**Comment by pitch314** [comment]
Bonjour WAT02110,

Dans la configuration du plugin Xtense, as-tu mis le token que tu as généré puis récupérer dans le mod Xtense ?

**Comment by WAT02110** [comment]
Bonjour,

Oui le token est collé, le serveur aussi.

De : pitch314 <notifications@github.com>
Envoyé : mardi 16 février 2021 21:25
À : OGSteam/tool-xtense-web-extension <tool-xtense-web-extension@noreply.github.com>
Cc : WAT02110 <victoiredavid2003@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [OGSteam/tool-xtense-web-extension] Les données envoyées ont été refusées par le plugin Xtense (#51)


Bonjour WAT02110,

Dans la configuration du plugin Xtense, as-tu mis le token que tu as généré puis récupérer dans le mod Xtense ?

**Comment by pitch314** [comment]
Pour une vision globale :

Version OGSpy : ? _[dernière version = 3.3.7]_
Version mod-Xtense : ? _[dernière version = 2.9.0]_
Version plugin-Xtense : v2.9.6 _[dernière version = Mozilla/Chrome 2.9.6]_
serveur OGSpy en HTTPS ?
Serveur OGSpy fournit par la team OGSpy (cf. Darknoon) ou sur son propre hébergement ?

Actions :
1. Peux-tu régénérer un token neuf puis l'utiliser dans le plugin ?
2. Vérifier que le login/mot de passe du compte OGSpy soit correct.

Si cela ne fonctionne toujours pas : 
(idéalement, ré-installer le plugin Xtense sur le navigateur)
1. Créer un nouvel utilisation OGSpy.
2. Générer sont token
3. Configurer son mod Xtense
4. Récupérer les informations du mod Xtense pour l'insérer dans le plugin Xtense
5. Tester la récupération des données avec cet nouvel utilisateur

**Comment by WAT02110** [comment]
Mes réponses ci-dessous

De : pitch314 <notifications@github.com>
Envoyé : mardi 16 février 2021 21:59
À : OGSteam/tool-xtense-web-extension <tool-xtense-web-extension@noreply.github.com>
Cc : WAT02110 <victoiredavid2003@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [OGSteam/tool-xtense-web-extension] Les données envoyées ont été refusées par le plugin Xtense (#51)


Pour une vision globale :

Version OGSpy : ? [dernière version = 3.3.7][David Victoire]  oui
Version mod-Xtense : ? [dernière version = 2.9.0][David Victoire]  2.7.8 comment puis je le up ? le serveur vient d’etre monté avec cette version.

Je vois des logs avec des pb d’update :

16/02/2021 22:03:05 : [administration] wat02110 [ERROR_github_Request] Unable to get: https://api.github.com/repos/ogsteam/ogspy/releases/latest
16/02/2021 22:02:24 : [autoupdate] wat02110 [ERROR_github_Request] Unable to get: https://api.github.com/orgs/ogsteam/repos?per_page=100

Version plugin-Xtense : v2.9.6 [dernière version = Mozilla/Chrome 2.9.6][David Victoire] oui
serveur OGSpy en HTTPS ?[David Victoire]  les 2 sont OK
Serveur OGSpy fournit par la team OGSpy (cf. Darknoon) ou sur son propre hébergement ?[David Victoire]  homemade



Actions :

  1.  Peux-tu régénérer un token neuf puis l'utiliser dans le plugin ?[David Victoire]  déjà tenté : KO
  2.  Vérifier que le login/mot de passe du compte OGSpy soit correct.[David Victoire]  je viens bien connecté sur le compte

Si cela ne fonctionne toujours pas :
(idéalement, ré-installer le plugin Xtense sur le navigateur)

[David Victoire] Je test tout ca

  1.  Créer un nouvel utilisation OGSpy.
  2.  Générer sont token
  3.  Configurer son mod Xtense
  4.  Récupérer les informations du mod Xtense pour l'insérer dans le plugin Xtense
  5.  Tester la récupération des données avec cet nouvel utilisateur

**Comment by WAT02110** [comment]
Le dernier test est KO.
un problème avec cette version de MOD peut etre ?

Je n’ai pas encore trouvé comment mettre à jour un mod manuellement. Suffit il de remplacer des fichiers ?

De : David Victoire
Envoyé : mardi 16 février 2021 22:18
À : OGSteam/tool-xtense-web-extension <reply@reply.github.com>; OGSteam/tool-xtense-web-extension <tool-xtense-web-extension@noreply.github.com>
Cc : Author <author@noreply.github.com>
Objet : RE: [OGSteam/tool-xtense-web-extension] Les données envoyées ont été refusées par le plugin Xtense (#51)

Mes réponses ci-dessous

De : pitch314 <notifications@github.com<mailto:notifications@github.com>>
Envoyé : mardi 16 février 2021 21:59
À : OGSteam/tool-xtense-web-extension <tool-xtense-web-extension@noreply.github.com<mailto:tool-xtense-web-extension@noreply.github.com>>
Cc : WAT02110 <victoiredavid2003@hotmail.com<mailto:victoiredavid2003@hotmail.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [OGSteam/tool-xtense-web-extension] Les données envoyées ont été refusées par le plugin Xtense (#51)


Pour une vision globale :

Version OGSpy : ? [dernière version = 3.3.7][David Victoire]  oui
Version mod-Xtense : ? [dernière version = 2.9.0][David Victoire]  2.7.8 comment puis je le up ? le serveur vient d’etre monté avec cette version.

Je vois des logs avec des pb d’update :

16/02/2021 22:03:05 : [administration] wat02110 [ERROR_github_Request] Unable to get: https://api.github.com/repos/ogsteam/ogspy/releases/latest
16/02/2021 22:02:24 : [autoupdate] wat02110 [ERROR_github_Request] Unable to get: https://api.github.com/orgs/ogsteam/repos?per_page=100

Version plugin-Xtense : v2.9.6 [dernière version = Mozilla/Chrome 2.9.6][David Victoire] oui
serveur OGSpy en HTTPS ?[David Victoire]  les 2 sont OK
Serveur OGSpy fournit par la team OGSpy (cf. Darknoon) ou sur son propre hébergement ?[David Victoire]  homemade



Actions :

  1.  Peux-tu régénérer un token neuf puis l'utiliser dans le plugin ?[David Victoire]  déjà tenté : KO
  2.  Vérifier que le login/mot de passe du compte OGSpy soit correct.[David Victoire]  je viens bien connecté sur le compte

Si cela ne fonctionne toujours pas :
(idéalement, ré-installer le plugin Xtense sur le navigateur)

[David Victoire] Je test tout ca

  1.  Créer un nouvel utilisation OGSpy.
  2.  Générer sont token
  3.  Configurer son mod Xtense
  4.  Récupérer les informations du mod Xtense pour l'insérer dans le plugin Xtense
  5.  Tester la récupération des données avec cet nouvel utilisateur

**Comment by pitch314** [comment]
OK, alors pour le problème avec autoupdate, on vient de le découvrir ...

La mise à jour des mods s'effectue par le mod autoupdate qui regarde la version présente dans Github (en échec actuellement)

=>Il faut passer par une mise à jour manuel du mod : 
1. dans Administration\Mod => désinstaller le mod Xtense
2. Récupérer la dernière version du mod Xtense sur Github : https://github.com/OGSteam/mod-xtense/releases
3. Aller dans le dossier Xtense de ton OGSpy : .../mod/xtense (de mémoire) et supprimer le contenu
4. Copier le contenu de l'archive récupéré en 2 dans ce dossier du mod
5. Se reconnecter à OGSpy, puis aller dans Administration/Mod puis faire installer
6. Vérifier la version de l'Xtense
7. Si c'est bon, générer un token et l'utiliser dans le plugin Xtense

**Comment by WAT02110** [comment]
Ahhhh 😃
Bah voilà !

C’est réglé, thx !

De : pitch314 <notifications@github.com>
Envoyé : mardi 16 février 2021 22:36
À : OGSteam/tool-xtense-web-extension <tool-xtense-web-extension@noreply.github.com>
Cc : WAT02110 <victoiredavid2003@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [OGSteam/tool-xtense-web-extension] Les données envoyées ont été refusées par le plugin Xtense (#51)


OK, alors pour le problème avec autoupdate, on vient de le découvrir ...

La mise à jour des mods s'effectue par le mod autoupdate qui regarde la version présente dans Github (en échec actuellement)

=>Il faut passer par une mise à jour manuel du mod :

  1.  dans Administration\Mod => désinstaller le mod Xtense
  2.  Récupérer la dernière version du mod Xtense sur Github : https://github.com/OGSteam/mod-xtense/releases
  3.  Aller dans le dossier Xtense de ton OGSpy : .../mod/xtense (de mémoire) et supprimer le contenu
  4.  Copier le contenu de l'archive récupéré en 2 dans ce dossier du mod
  5.  Se reconnecter à OGSpy, puis aller dans Administration/Mod puis faire installer
  6.  Vérifier la version de l'Xtense
  7.  Si c'est bon, générer un token et l'utiliser dans le plugin Xtense

**Comment by pitch314** [comment]
OK, super.

Bonne continuation.
