### ISSUE TITLE
Case production qui se décoche

### ISSUE THREAD

**Issue by LuCarD84** [OGSteam/tool-xtense-web-extension#57]
Bonjour je viens remonter un bug

Quand je coche la case production dans xtense

je passe sur une autre pages (galaxie, flotte....) et que je retourne dans xtense la case n'est plus cochée apparement elle se décoche toute seule

Xtense 2.9.8
Chrome 98.0.4758.102 (Build officiel) (64 bits)

https://i.imgur.com/KYoW95d.png

**Comment by darknoon29** [comment]
Fixed for the next Release
