### ISSUE TITLE
Page ressources

### ISSUE THREAD

**Issue by machine62** [OGSteam/tool-xtense-web-extension#63]
Deux url possible pour voir les % de prod des ressources ingame

index.php?page=ingame&component=resourcesettings
et 
index.php?page=resourceSettings

le contenu est le meme mais seule la seconde est traité par xtense 
![bugxtense](https://github.com/OGSteam/tool-xtense-web-extension/assets/28401480/2b478588-8616-4331-971f-68fa0be18ac1)

**Comment by satepestage** [comment]
Je confirme que j'ai le même problème sur mon propre OGSpy.

**Comment by darknoon29** [comment]
Est ce qu'il y a une correspondace avec la version du jeu ?

**Comment by satepestage** [comment]
Avec machine, nous avons testé : 
* 2 univers différents
* 2 serveurs OGSpy différents (3.3.8 à jour)
* (je pense des navigateurs différents - Chrome pour ma part)
Je précise également que j'ai remarqué la différence d'URL depuis mon tel sans aucun autre script.

**Comment by machine62** [comment]
Firefox pour moi.
version du jeu : 9.2.3 [© 2002 Gameforge 4D GmbH. Tous droits réservés.](http://www.gameforge.com/)
